BlogSampleV2.WebUI/Controllers/GuestBookController.cs
using BlogSampleV2.Domain.Interfaces;
using BlogSampleV2.WebUI.Models;
using System.Linq;
using System.Web.Mvc;

namespace BlogSampleV2.WebUI.Controllers
{
    public class GuestBookController : Controller
    {
        private IBlogRepository repository;
        public int PageSize = 6;

        public GuestBookController(IBlogRepository repository)
        {
            this.repository = repository;
        }

        // GET: Article
        public ViewResult Feedbacks(int page = 1)
        {
            FeedbacksViewModel model = new FeedbacksViewModel
            {
                Feedbacks = repository.Feedbacks
                                      .OrderBy(art => art.PostedDate)
                                      .Skip((page - 1) * PageSize)
                                      .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.Feedbacks.Count()
                }
            };
            return View(model);
        }

        [HttpPost]
        public ViewResult Feedbacks(string fName, string lName, string feedback)
        {  
            repository.AddFeedback(fName, lName, feedback);
            return Feedbacks();
        }
    }
}

BlogSampleV2.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/styles.css")
</head>
<body>
    <header>
        <div class="content">
            <h2 class="left">Blog sample V2</h2>
            <img src="~/Content/Imgs/Logo.jpg" class="right logo" alt="logo lies here" />
            <div class="clearfix"></div>
        </div>
    </header>
    <div class="content">
        <nav class="right-sidebar right">
            <ul>
                <li>@Html.ActionLink("Home", "Articles", "Home", null, new { @class = "menu-button" })</li>
                <li>@Html.ActionLink("Guest Book", "Feedbacks", "GuestBook", null, new { @class = "menu-button" })</li>
                <li>@Html.ActionLink("Questionnaire", "UpdateInfo", "Questionnaire", null, new { @class = "menu-button" })</li>
                <li>@Html.RouteLink("Administration", "Administration_short", null, new { @class = "menu-button" })</li>
            </ul>
            @RenderSection("Voting", false)
        </nav>
        <div class="main-body">
            @RenderBody()
        </div>
        <div class="clearfix"></div>
    </div>
    <footer>
        <div class="content">
            <h2 class="left">&copy Copyright @DateTime.Now.Year</h2>
            <div class="clearfix"></div>
        </div>
    </footer>
    <button onclick="topFunction()" id="topBtn" title="Go to top">Back to top</button>
    <script>
        // When the user scrolls down 100px from the top of the document, show the button
        window.onscroll = function () { scrollFunction() };

        function scrollFunction() {
            if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
                document.getElementById("topBtn").style.display = "block";
            }
            else {
                document.getElementById("topBtn").style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>
</body>
</html>