BlogSampleV2.WebUI/Models/QuestionnaireViewModel.cs
using BlogSampleV2.Domain.Entities;
using System.Collections.Generic;

namespace BlogSampleV2.WebUI.Models
{
    public class QuestionnaireViewModel
    {
        public BlogUser User { get; set; }
        public IEnumerable<Skill> Skills { get; set; }
    }
}

BlogSampleV2.WebUI/Controllers/QuestionnaireController.cs
using BlogSampleV2.Domain.Entities;
using BlogSampleV2.Domain.Interfaces;
using BlogSampleV2.WebUI.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BlogSampleV2.WebUI.Controllers
{
    public class QuestionnaireController : Controller
    {
        private IBlogRepository repository;

        public QuestionnaireController(IBlogRepository repository)
        {
            this.repository = repository;
        }

        // GET: Questionnaire
        public ViewResult UpdateInfo()
        {
            QuestionnaireViewModel model = new QuestionnaireViewModel();
            model.Skills = repository.Skills;
            return View(model);
        }

        [AcceptVerbs("POST", "GET")]
        public ViewResult Result(QuestionnaireViewModel model, List<string> skills)
        {
            model.User.Skills = new List<Skill>();
            if(skills != null)
            {
                foreach (var s in skills)
                {
                    model.User.Skills.Add(repository.Skills.Where(sk => sk.Name == s).First());
                }
            }            
            repository.AddUser(model.User);
            return View(model);
        }
    }
}

BlogSampleV2.WebUI/Views/Questionnaire/Result.cshtml
@model BlogSampleV2.WebUI.Models.QuestionnaireViewModel

@{
    ViewBag.Title = "Result";
}

<h2>Result</h2>


<p>First name: <strong>@Html.DisplayFor(u => u.User.FirstName)</strong></p>
<p>Last name: <strong>@Html.DisplayFor(u => u.User.LastName)</strong></p>
<p>Nickname: <strong>@Html.DisplayFor(u => u.User.Nick)</strong></p>
<p>Gender: <strong>@Html.DisplayFor(u => u.User.Gender)</strong></p>
@if (Model.User.Skills.Count > 0)
{
    <p>
        Skills: <ul>
            @foreach (var skill in Model.User.Skills)
            {
                <li><strong>@(skill.Name)</strong></li>
            }
        </ul>
    </p>
}

BlogSampleV2.WebUI/Views/Questionnaire/UpdateInfo.cshtml
@model BlogSampleV2.WebUI.Models.QuestionnaireViewModel

@{
    ViewBag.Title = "Update Info";
}

<h2>Update Info</h2>

@using (Html.BeginForm("Result", "Questionnaire"))
{
    <p>First name:</p>    
    @Html.EditorFor(model => model.User.FirstName)
    <p>Last name:</p>   
    @Html.EditorFor(model => model.User.LastName)
    <p>Nickname:</p>   
    @Html.EditorFor(model => model.User.Nick)
    <p>Gender:</p>
    <p>Female: @Html.RadioButtonFor(model => model.User.Gender, "Female", new { @checked = "checked" })</p>
    <p>Male: @Html.RadioButtonFor(model => model.User.Gender, "Male")</p><br />
    

    <p>Skills:</p>
    @Html.CreateCheckedSkillList(@Model.Skills)

    <p><input type="submit" value="Update info"></p>
}